// Generated by https://quicktype.io

export interface LinkResponse {
    message: string;
    link: Link;
}

export interface Link {
    _id?:         string;
    title:       string;
    url:         string;
    description: string;
    createdAt?:   string;
    updatedAt?:   string;
}